<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.CSharp2VB = New System.Windows.Forms.RadioButton()
        Me.VB2CSharp = New System.Windows.Forms.RadioButton()
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
        Me.FileToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripMenuItem1 = New System.Windows.Forms.ToolStripMenuItem()
        Me.OpenFileToolStripMenuItem1 = New System.Windows.Forms.ToolStripMenuItem()
        Me.OpenProjectToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator6 = New System.Windows.Forms.ToolStripSeparator()
        Me.RecentFilesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.RecentFile1ToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.RecentFoldersToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.RecentFolder1ToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator7 = New System.Windows.Forms.ToolStripSeparator()
        Me.SaveAsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator2 = New System.Windows.Forms.ToolStripSeparator()
        Me.SnippetToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.SnippetLoadLastToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.SnippetSaveToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator5 = New System.Windows.Forms.ToolStripSeparator()
        Me.ExitToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.EditToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.FIndToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.CutToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.CopyToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.PasteToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.UndoToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.OptionsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.AutoCompileToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ColorizeResultToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ColorizeSourceToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.DelayBetweenConversionsToolStripMenuItem = New System.Windows.Forms.ToolStripComboBox()
        Me.ToolStripSeparator4 = New System.Windows.Forms.ToolStripSeparator()
        Me.MiscellaneousOptionsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.PauseConvertOnSuccessToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripSeparator3 = New System.Windows.Forms.ToolStripSeparator()
        Me.SkipAutoGeneratedToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.StartFolderConvertFromLastFileToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.SkipTestResourceFilesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.CompileToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ConvertToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ConvertProjectToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ConvertFolderToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ConvertSnipitToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ViewToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.InputBufferLineNumbersToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.OuputBufferLineNumbersToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.HelpToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.SaveFileDialog1 = New System.Windows.Forms.SaveFileDialog()
        Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
        Me.ContextMenuStrip1 = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.ToolStripMenuItem_Copy = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripMenuItem_Cut = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripMenuItem_Paste = New System.Windows.Forms.ToolStripMenuItem()
        Me.SearchInput = New System.Windows.Forms.TextBox()
        Me.ImageList1 = New System.Windows.Forms.ImageList(Me.components)
        Me.SearchDirection = New System.Windows.Forms.ComboBox()
        Me.SearchWhere = New System.Windows.Forms.ComboBox()
        Me.InputFolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog()
        Me.OutputFolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog()
        Me.PictureBox1 = New System.Windows.Forms.PictureBox()
        Me.ButtonSearch = New System.Windows.Forms.Button()
        Me.ButtonStop = New System.Windows.Forms.Button()
        Me.LabelErrorCount = New System.Windows.Forms.Label()
        Me.ToolTip1 = New System.Windows.Forms.ToolTip(Me.components)
        Me.SplitContainer1 = New System.Windows.Forms.SplitContainer()
        Me.RichTextBoxConversionInput = New System.Windows.Forms.RichTextBox()
        Me.RichTextBoxFileList = New System.Windows.Forms.RichTextBox()
        Me.RichTextBoxErrorList = New System.Windows.Forms.RichTextBox()
        Me.ProgressBar1 = New System.Windows.Forms.ProgressBar()
        Me.LineNumbers_For_RichTextBoxInput = New CSharpToVBApp.LineNumbers_For_RichTextBox()
        Me.RichTextBoxConversionOutput = New CSharpToVBApp.AdvancedRTB()
        Me.LineNumbers_For_RichTextBoxOutput = New CSharpToVBApp.LineNumbers_For_RichTextBox()
        Me.MenuStrip1.SuspendLayout()
        Me.ContextMenuStrip1.SuspendLayout()
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        Me.SuspendLayout()
        '
        'CSharp2VB
        '
        Me.CSharp2VB.AutoSize = True
        Me.CSharp2VB.Checked = True
        Me.CSharp2VB.Location = New System.Drawing.Point(1621, 5)
        Me.CSharp2VB.Name = "CSharp2VB"
        Me.CSharp2VB.Size = New System.Drawing.Size(72, 17)
        Me.CSharp2VB.TabIndex = 3
        Me.CSharp2VB.TabStop = True
        Me.CSharp2VB.Text = "C# To VB"
        Me.CSharp2VB.UseVisualStyleBackColor = True
        '
        'VB2CSharp
        '
        Me.VB2CSharp.AutoSize = True
        Me.VB2CSharp.Location = New System.Drawing.Point(1699, 5)
        Me.VB2CSharp.Name = "VB2CSharp"
        Me.VB2CSharp.Size = New System.Drawing.Size(72, 17)
        Me.VB2CSharp.TabIndex = 4
        Me.VB2CSharp.Text = "VB To C#"
        Me.VB2CSharp.UseVisualStyleBackColor = True
        Me.VB2CSharp.Visible = False
        '
        'MenuStrip1
        '
        Me.MenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.FileToolStripMenuItem, Me.EditToolStripMenuItem, Me.OptionsToolStripMenuItem, Me.CompileToolStripMenuItem, Me.ConvertToolStripMenuItem, Me.ViewToolStripMenuItem, Me.HelpToolStripMenuItem})
        Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Size = New System.Drawing.Size(1648, 24)
        Me.MenuStrip1.TabIndex = 7
        Me.MenuStrip1.Text = "MenuStrip1"
        '
        'FileToolStripMenuItem
        '
        Me.FileToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ToolStripMenuItem1, Me.ToolStripSeparator6, Me.RecentFilesToolStripMenuItem, Me.RecentFoldersToolStripMenuItem, Me.ToolStripSeparator7, Me.SaveAsToolStripMenuItem, Me.ToolStripSeparator2, Me.SnippetToolStripMenuItem, Me.ToolStripSeparator5, Me.ExitToolStripMenuItem})
        Me.FileToolStripMenuItem.Name = "FileToolStripMenuItem"
        Me.FileToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.FileToolStripMenuItem.Size = New System.Drawing.Size(37, 20)
        Me.FileToolStripMenuItem.Text = "&File"
        '
        'ToolStripMenuItem1
        '
        Me.ToolStripMenuItem1.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.OpenFileToolStripMenuItem1, Me.OpenProjectToolStripMenuItem})
        Me.ToolStripMenuItem1.Name = "ToolStripMenuItem1"
        Me.ToolStripMenuItem1.Size = New System.Drawing.Size(180, 22)
        Me.ToolStripMenuItem1.Text = "Open"
        '
        'OpenFileToolStripMenuItem1
        '
        Me.OpenFileToolStripMenuItem1.Name = "OpenFileToolStripMenuItem1"
        Me.OpenFileToolStripMenuItem1.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.OpenFileToolStripMenuItem1.Size = New System.Drawing.Size(227, 22)
        Me.OpenFileToolStripMenuItem1.Text = "&Open File..."
        '
        'OpenProjectToolStripMenuItem
        '
        Me.OpenProjectToolStripMenuItem.Name = "OpenProjectToolStripMenuItem"
        Me.OpenProjectToolStripMenuItem.ShortcutKeys = CType(((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Shift) _
            Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.OpenProjectToolStripMenuItem.Size = New System.Drawing.Size(227, 22)
        Me.OpenProjectToolStripMenuItem.Text = "Open Project..."
        '
        'ToolStripSeparator6
        '
        Me.ToolStripSeparator6.Name = "ToolStripSeparator6"
        Me.ToolStripSeparator6.Size = New System.Drawing.Size(177, 6)
        '
        'RecentFilesToolStripMenuItem
        '
        Me.RecentFilesToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.RecentFile1ToolStripMenuItem})
        Me.RecentFilesToolStripMenuItem.Name = "RecentFilesToolStripMenuItem"
        Me.RecentFilesToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.RecentFilesToolStripMenuItem.Text = "Recent Files"
        '
        'RecentFile1ToolStripMenuItem
        '
        Me.RecentFile1ToolStripMenuItem.Name = "RecentFile1ToolStripMenuItem"
        Me.RecentFile1ToolStripMenuItem.Size = New System.Drawing.Size(134, 22)
        Me.RecentFile1ToolStripMenuItem.Text = "RecentFile1"
        Me.RecentFile1ToolStripMenuItem.Visible = False
        '
        'RecentFoldersToolStripMenuItem
        '
        Me.RecentFoldersToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.RecentFolder1ToolStripMenuItem})
        Me.RecentFoldersToolStripMenuItem.Name = "RecentFoldersToolStripMenuItem"
        Me.RecentFoldersToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.RecentFoldersToolStripMenuItem.Text = "Recent Folders"
        '
        'RecentFolder1ToolStripMenuItem
        '
        Me.RecentFolder1ToolStripMenuItem.Name = "RecentFolder1ToolStripMenuItem"
        Me.RecentFolder1ToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.RecentFolder1ToolStripMenuItem.Text = "RecentFolder1"
        '
        'ToolStripSeparator7
        '
        Me.ToolStripSeparator7.Name = "ToolStripSeparator7"
        Me.ToolStripSeparator7.Size = New System.Drawing.Size(177, 6)
        '
        'SaveAsToolStripMenuItem
        '
        Me.SaveAsToolStripMenuItem.Enabled = False
        Me.SaveAsToolStripMenuItem.Name = "SaveAsToolStripMenuItem"
        Me.SaveAsToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.SaveAsToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.SaveAsToolStripMenuItem.Text = "Save &As..."
        '
        'ToolStripSeparator2
        '
        Me.ToolStripSeparator2.Name = "ToolStripSeparator2"
        Me.ToolStripSeparator2.Size = New System.Drawing.Size(177, 6)
        '
        'SnippetToolStripMenuItem
        '
        Me.SnippetToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.SnippetLoadLastToolStripMenuItem, Me.SnippetSaveToolStripMenuItem})
        Me.SnippetToolStripMenuItem.Name = "SnippetToolStripMenuItem"
        Me.SnippetToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.SnippetToolStripMenuItem.Text = "Snippet"
        '
        'SnippetLoadLastToolStripMenuItem
        '
        Me.SnippetLoadLastToolStripMenuItem.Enabled = False
        Me.SnippetLoadLastToolStripMenuItem.Name = "SnippetLoadLastToolStripMenuItem"
        Me.SnippetLoadLastToolStripMenuItem.Size = New System.Drawing.Size(124, 22)
        Me.SnippetLoadLastToolStripMenuItem.Text = "Load Last"
        '
        'SnippetSaveToolStripMenuItem
        '
        Me.SnippetSaveToolStripMenuItem.Enabled = False
        Me.SnippetSaveToolStripMenuItem.Name = "SnippetSaveToolStripMenuItem"
        Me.SnippetSaveToolStripMenuItem.Size = New System.Drawing.Size(124, 22)
        Me.SnippetSaveToolStripMenuItem.Text = "Save"
        '
        'ToolStripSeparator5
        '
        Me.ToolStripSeparator5.Name = "ToolStripSeparator5"
        Me.ToolStripSeparator5.Size = New System.Drawing.Size(177, 6)
        '
        'ExitToolStripMenuItem
        '
        Me.ExitToolStripMenuItem.Name = "ExitToolStripMenuItem"
        Me.ExitToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.ExitToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.ExitToolStripMenuItem.Text = "E&xit"
        '
        'EditToolStripMenuItem
        '
        Me.EditToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.FIndToolStripMenuItem, Me.ToolStripSeparator1, Me.CutToolStripMenuItem, Me.CopyToolStripMenuItem, Me.PasteToolStripMenuItem, Me.UndoToolStripMenuItem})
        Me.EditToolStripMenuItem.Name = "EditToolStripMenuItem"
        Me.EditToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.E), System.Windows.Forms.Keys)
        Me.EditToolStripMenuItem.Size = New System.Drawing.Size(39, 20)
        Me.EditToolStripMenuItem.Text = "&Edit"
        '
        'FIndToolStripMenuItem
        '
        Me.FIndToolStripMenuItem.Name = "FIndToolStripMenuItem"
        Me.FIndToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.FIndToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.FIndToolStripMenuItem.Text = "FInd..."
        '
        'ToolStripSeparator1
        '
        Me.ToolStripSeparator1.Name = "ToolStripSeparator1"
        Me.ToolStripSeparator1.Size = New System.Drawing.Size(143, 6)
        '
        'CutToolStripMenuItem
        '
        Me.CutToolStripMenuItem.Name = "CutToolStripMenuItem"
        Me.CutToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.CutToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.CutToolStripMenuItem.Text = "Cut"
        '
        'CopyToolStripMenuItem
        '
        Me.CopyToolStripMenuItem.Name = "CopyToolStripMenuItem"
        Me.CopyToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.CopyToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.CopyToolStripMenuItem.Text = "Copy"
        '
        'PasteToolStripMenuItem
        '
        Me.PasteToolStripMenuItem.Name = "PasteToolStripMenuItem"
        Me.PasteToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.PasteToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.PasteToolStripMenuItem.Text = "Paste"
        '
        'UndoToolStripMenuItem
        '
        Me.UndoToolStripMenuItem.Name = "UndoToolStripMenuItem"
        Me.UndoToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.UndoToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.UndoToolStripMenuItem.Text = "Undo"
        '
        'OptionsToolStripMenuItem
        '
        Me.OptionsToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.AutoCompileToolStripMenuItem, Me.ColorizeResultToolStripMenuItem, Me.ColorizeSourceToolStripMenuItem, Me.DelayBetweenConversionsToolStripMenuItem, Me.ToolStripSeparator4, Me.MiscellaneousOptionsToolStripMenuItem, Me.PauseConvertOnSuccessToolStripMenuItem, Me.ToolStripSeparator3, Me.SkipAutoGeneratedToolStripMenuItem, Me.StartFolderConvertFromLastFileToolStripMenuItem, Me.SkipTestResourceFilesToolStripMenuItem})
        Me.OptionsToolStripMenuItem.Name = "OptionsToolStripMenuItem"
        Me.OptionsToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.OptionsToolStripMenuItem.Size = New System.Drawing.Size(61, 20)
        Me.OptionsToolStripMenuItem.Text = "&Options"
        '
        'AutoCompileToolStripMenuItem
        '
        Me.AutoCompileToolStripMenuItem.Checked = True
        Me.AutoCompileToolStripMenuItem.CheckOnClick = True
        Me.AutoCompileToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.AutoCompileToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.AutoCompileToolStripMenuItem.Name = "AutoCompileToolStripMenuItem"
        Me.AutoCompileToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.AutoCompileToolStripMenuItem.Text = "Auto Comipile"
        '
        'ColorizeResultToolStripMenuItem
        '
        Me.ColorizeResultToolStripMenuItem.CheckOnClick = True
        Me.ColorizeResultToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ColorizeResultToolStripMenuItem.Name = "ColorizeResultToolStripMenuItem"
        Me.ColorizeResultToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.ColorizeResultToolStripMenuItem.Text = "Colorize Result"
        '
        'ColorizeSourceToolStripMenuItem
        '
        Me.ColorizeSourceToolStripMenuItem.CheckOnClick = True
        Me.ColorizeSourceToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ColorizeSourceToolStripMenuItem.Name = "ColorizeSourceToolStripMenuItem"
        Me.ColorizeSourceToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.ColorizeSourceToolStripMenuItem.Text = "Colorize Source"
        '
        'DelayBetweenConversionsToolStripMenuItem
        '
        Me.DelayBetweenConversionsToolStripMenuItem.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.DelayBetweenConversionsToolStripMenuItem.Items.AddRange(New Object() {"Delay Between Conversions = None", "Delay Between Conversions = 5 Seconds", "Delay Between Conversions = 10 Seconds"})
        Me.DelayBetweenConversionsToolStripMenuItem.Name = "DelayBetweenConversionsToolStripMenuItem"
        Me.DelayBetweenConversionsToolStripMenuItem.Size = New System.Drawing.Size(481, 23)
        '
        'ToolStripSeparator4
        '
        Me.ToolStripSeparator4.Name = "ToolStripSeparator4"
        Me.ToolStripSeparator4.Size = New System.Drawing.Size(538, 6)
        '
        'MiscellaneousOptionsToolStripMenuItem
        '
        Me.MiscellaneousOptionsToolStripMenuItem.Name = "MiscellaneousOptionsToolStripMenuItem"
        Me.MiscellaneousOptionsToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.MiscellaneousOptionsToolStripMenuItem.Text = "Miscellaneous Options"
        '
        'PauseConvertOnSuccessToolStripMenuItem
        '
        Me.PauseConvertOnSuccessToolStripMenuItem.CheckOnClick = True
        Me.PauseConvertOnSuccessToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.PauseConvertOnSuccessToolStripMenuItem.Name = "PauseConvertOnSuccessToolStripMenuItem"
        Me.PauseConvertOnSuccessToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.PauseConvertOnSuccessToolStripMenuItem.Text = "Pause Conversion on Success"
        '
        'ToolStripSeparator3
        '
        Me.ToolStripSeparator3.Name = "ToolStripSeparator3"
        Me.ToolStripSeparator3.Size = New System.Drawing.Size(538, 6)
        '
        'SkipAutoGeneratedToolStripMenuItem
        '
        Me.SkipAutoGeneratedToolStripMenuItem.Checked = True
        Me.SkipAutoGeneratedToolStripMenuItem.CheckOnClick = True
        Me.SkipAutoGeneratedToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.SkipAutoGeneratedToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.SkipAutoGeneratedToolStripMenuItem.Name = "SkipAutoGeneratedToolStripMenuItem"
        Me.SkipAutoGeneratedToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.SkipAutoGeneratedToolStripMenuItem.Text = "Skip AutoGenerated"
        '
        'StartFolderConvertFromLastFileToolStripMenuItem
        '
        Me.StartFolderConvertFromLastFileToolStripMenuItem.Checked = True
        Me.StartFolderConvertFromLastFileToolStripMenuItem.CheckOnClick = True
        Me.StartFolderConvertFromLastFileToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.StartFolderConvertFromLastFileToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.StartFolderConvertFromLastFileToolStripMenuItem.Name = "StartFolderConvertFromLastFileToolStripMenuItem"
        Me.StartFolderConvertFromLastFileToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.StartFolderConvertFromLastFileToolStripMenuItem.Text = "Start Convert Folder From Last File"
        '
        'SkipTestResourceFilesToolStripMenuItem
        '
        Me.SkipTestResourceFilesToolStripMenuItem.Checked = True
        Me.SkipTestResourceFilesToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.SkipTestResourceFilesToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.SkipTestResourceFilesToolStripMenuItem.Name = "SkipTestResourceFilesToolStripMenuItem"
        Me.SkipTestResourceFilesToolStripMenuItem.Size = New System.Drawing.Size(541, 22)
        Me.SkipTestResourceFilesToolStripMenuItem.Text = "Skip Test Resource Files"
        '
        'CompileToolStripMenuItem
        '
        Me.CompileToolStripMenuItem.Enabled = False
        Me.CompileToolStripMenuItem.Name = "CompileToolStripMenuItem"
        Me.CompileToolStripMenuItem.Size = New System.Drawing.Size(64, 20)
        Me.CompileToolStripMenuItem.Text = "Compile"
        '
        'ConvertToolStripMenuItem
        '
        Me.ConvertToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ConvertProjectToolStripMenuItem, Me.ConvertFolderToolStripMenuItem, Me.ConvertSnipitToolStripMenuItem})
        Me.ConvertToolStripMenuItem.Name = "ConvertToolStripMenuItem"
        Me.ConvertToolStripMenuItem.Size = New System.Drawing.Size(61, 20)
        Me.ConvertToolStripMenuItem.Text = "Convert"
        '
        'ConvertProjectToolStripMenuItem
        '
        Me.ConvertProjectToolStripMenuItem.Enabled = False
        Me.ConvertProjectToolStripMenuItem.Name = "ConvertProjectToolStripMenuItem"
        Me.ConvertProjectToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.P), System.Windows.Forms.Keys)
        Me.ConvertProjectToolStripMenuItem.Size = New System.Drawing.Size(199, 22)
        Me.ConvertProjectToolStripMenuItem.Text = "Convert Project"
        '
        'ConvertFolderToolStripMenuItem
        '
        Me.ConvertFolderToolStripMenuItem.Name = "ConvertFolderToolStripMenuItem"
        Me.ConvertFolderToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.ConvertFolderToolStripMenuItem.Size = New System.Drawing.Size(199, 22)
        Me.ConvertFolderToolStripMenuItem.Text = "Convert Folder"
        '
        'ConvertSnipitToolStripMenuItem
        '
        Me.ConvertSnipitToolStripMenuItem.Enabled = False
        Me.ConvertSnipitToolStripMenuItem.Name = "ConvertSnipitToolStripMenuItem"
        Me.ConvertSnipitToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.S), System.Windows.Forms.Keys)
        Me.ConvertSnipitToolStripMenuItem.Size = New System.Drawing.Size(199, 22)
        Me.ConvertSnipitToolStripMenuItem.Text = "Convert Snippet"
        '
        'ViewToolStripMenuItem
        '
        Me.ViewToolStripMenuItem.CheckOnClick = True
        Me.ViewToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.InputBufferLineNumbersToolStripMenuItem, Me.OuputBufferLineNumbersToolStripMenuItem})
        Me.ViewToolStripMenuItem.Name = "ViewToolStripMenuItem"
        Me.ViewToolStripMenuItem.Size = New System.Drawing.Size(44, 20)
        Me.ViewToolStripMenuItem.Text = "View"
        '
        'InputBufferLineNumbersToolStripMenuItem
        '
        Me.InputBufferLineNumbersToolStripMenuItem.CheckOnClick = True
        Me.InputBufferLineNumbersToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.InputBufferLineNumbersToolStripMenuItem.Name = "InputBufferLineNumbersToolStripMenuItem"
        Me.InputBufferLineNumbersToolStripMenuItem.Size = New System.Drawing.Size(220, 22)
        Me.InputBufferLineNumbersToolStripMenuItem.Text = "Input Buffer Line Numbers"
        '
        'OuputBufferLineNumbersToolStripMenuItem
        '
        Me.OuputBufferLineNumbersToolStripMenuItem.CheckOnClick = True
        Me.OuputBufferLineNumbersToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.OuputBufferLineNumbersToolStripMenuItem.Name = "OuputBufferLineNumbersToolStripMenuItem"
        Me.OuputBufferLineNumbersToolStripMenuItem.Size = New System.Drawing.Size(220, 22)
        Me.OuputBufferLineNumbersToolStripMenuItem.Text = "Ouput Buffer Line Numbers"
        '
        'HelpToolStripMenuItem
        '
        Me.HelpToolStripMenuItem.Name = "HelpToolStripMenuItem"
        Me.HelpToolStripMenuItem.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.H), System.Windows.Forms.Keys)
        Me.HelpToolStripMenuItem.Size = New System.Drawing.Size(44, 20)
        Me.HelpToolStripMenuItem.Text = "&Help"
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'ContextMenuStrip1
        '
        Me.ContextMenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.ContextMenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ToolStripMenuItem_Copy, Me.ToolStripMenuItem_Cut, Me.ToolStripMenuItem_Paste})
        Me.ContextMenuStrip1.Name = "ContextMenuStrip1"
        Me.ContextMenuStrip1.Size = New System.Drawing.Size(103, 70)
        '
        'ToolStripMenuItem_Copy
        '
        Me.ToolStripMenuItem_Copy.Name = "ToolStripMenuItem_Copy"
        Me.ToolStripMenuItem_Copy.Size = New System.Drawing.Size(102, 22)
        Me.ToolStripMenuItem_Copy.Text = "Copy"
        '
        'ToolStripMenuItem_Cut
        '
        Me.ToolStripMenuItem_Cut.Name = "ToolStripMenuItem_Cut"
        Me.ToolStripMenuItem_Cut.Size = New System.Drawing.Size(102, 22)
        Me.ToolStripMenuItem_Cut.Text = "Cut"
        '
        'ToolStripMenuItem_Paste
        '
        Me.ToolStripMenuItem_Paste.Name = "ToolStripMenuItem_Paste"
        Me.ToolStripMenuItem_Paste.Size = New System.Drawing.Size(102, 22)
        Me.ToolStripMenuItem_Paste.Text = "Paste"
        '
        'SearchInput
        '
        Me.SearchInput.Location = New System.Drawing.Point(800, 3)
        Me.SearchInput.Name = "SearchInput"
        Me.SearchInput.Size = New System.Drawing.Size(168, 20)
        Me.SearchInput.TabIndex = 10
        '
        'ImageList1
        '
        Me.ImageList1.ImageStream = CType(resources.GetObject("ImageList1.ImageStream"), System.Windows.Forms.ImageListStreamer)
        Me.ImageList1.TransparentColor = System.Drawing.Color.Transparent
        Me.ImageList1.Images.SetKeyName(0, "arrow_Forward_16xLG.png")
        Me.ImageList1.Images.SetKeyName(1, "arrow_back_16xLG.png")
        '
        'SearchDirection
        '
        Me.SearchDirection.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawVariable
        Me.SearchDirection.FormattingEnabled = True
        Me.SearchDirection.Location = New System.Drawing.Point(979, 2)
        Me.SearchDirection.Name = "SearchDirection"
        Me.SearchDirection.Size = New System.Drawing.Size(53, 21)
        Me.SearchDirection.TabIndex = 11
        '
        'SearchWhere
        '
        Me.SearchWhere.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.SearchWhere.FormattingEnabled = True
        Me.SearchWhere.Items.AddRange(New Object() {"Search Input Buffer", "Search OutPut Buffer", "Search Both"})
        Me.SearchWhere.Location = New System.Drawing.Point(632, 3)
        Me.SearchWhere.Name = "SearchWhere"
        Me.SearchWhere.Size = New System.Drawing.Size(159, 21)
        Me.SearchWhere.TabIndex = 14
        '
        'InputFolderBrowserDialog1
        '
        Me.InputFolderBrowserDialog1.RootFolder = System.Environment.SpecialFolder.CommonDocuments
        Me.InputFolderBrowserDialog1.ShowNewFolderButton = False
        '
        'OutputFolderBrowserDialog1
        '
        Me.OutputFolderBrowserDialog1.RootFolder = System.Environment.SpecialFolder.CommonDocuments
        '
        'PictureBox1
        '
        Me.PictureBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.PictureBox1.Location = New System.Drawing.Point(974, 1)
        Me.PictureBox1.Name = "PictureBox1"
        Me.PictureBox1.Size = New System.Drawing.Size(27, 21)
        Me.PictureBox1.TabIndex = 13
        Me.PictureBox1.TabStop = False
        '
        'ButtonSearch
        '
        Me.ButtonSearch.BackColor = System.Drawing.SystemColors.ButtonFace
        Me.ButtonSearch.Image = CType(resources.GetObject("ButtonSearch.Image"), System.Drawing.Image)
        Me.ButtonSearch.Location = New System.Drawing.Point(1035, 1)
        Me.ButtonSearch.Name = "ButtonSearch"
        Me.ButtonSearch.Size = New System.Drawing.Size(33, 23)
        Me.ButtonSearch.TabIndex = 12
        Me.ToolTip1.SetToolTip(Me.ButtonSearch, "Close Search")
        Me.ButtonSearch.UseVisualStyleBackColor = False
        '
        'ButtonStop
        '
        Me.ButtonStop.Location = New System.Drawing.Point(1169, 1)
        Me.ButtonStop.Name = "ButtonStop"
        Me.ButtonStop.Size = New System.Drawing.Size(70, 23)
        Me.ButtonStop.TabIndex = 19
        Me.ButtonStop.Text = "Stop Conversion"
        Me.ButtonStop.UseVisualStyleBackColor = True
        Me.ButtonStop.Visible = False
        '
        'LabelErrorCount
        '
        Me.LabelErrorCount.AutoSize = True
        Me.LabelErrorCount.Location = New System.Drawing.Point(1254, 6)
        Me.LabelErrorCount.Name = "LabelErrorCount"
        Me.LabelErrorCount.Size = New System.Drawing.Size(98, 13)
        Me.LabelErrorCount.TabIndex = 20
        Me.LabelErrorCount.Text = "Number of Errors: 0"
        '
        'ToolTip1
        '
        Me.ToolTip1.ToolTipTitle = "Close Search"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.BackColor = System.Drawing.SystemColors.HotTrack
        Me.SplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2
        Me.SplitContainer1.Location = New System.Drawing.Point(0, 24)
        Me.SplitContainer1.Name = "SplitContainer1"
        Me.SplitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.RichTextBoxConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbers_For_RichTextBoxInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.RichTextBoxConversionOutput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbers_For_RichTextBoxOutput)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.RichTextBoxFileList)
        Me.SplitContainer1.Panel2.Controls.Add(Me.RichTextBoxErrorList)
        Me.SplitContainer1.Size = New System.Drawing.Size(1648, 528)
        Me.SplitContainer1.SplitterDistance = 80
        Me.SplitContainer1.TabIndex = 22
        '
        'RichTextBoxConversionInput
        '
        Me.RichTextBoxConversionInput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.RichTextBoxConversionInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.RichTextBoxConversionInput.Font = New System.Drawing.Font("Consolas", 11.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.RichTextBoxConversionInput.Location = New System.Drawing.Point(20, 0)
        Me.RichTextBoxConversionInput.Name = "RichTextBoxConversionInput"
        Me.RichTextBoxConversionInput.Size = New System.Drawing.Size(1047, 80)
        Me.RichTextBoxConversionInput.TabIndex = 9
        Me.RichTextBoxConversionInput.Text = ""
        Me.RichTextBoxConversionInput.WordWrap = False
        '
        'RichTextBoxFileList
        '
        Me.RichTextBoxFileList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.RichTextBoxFileList.HideSelection = False
        Me.RichTextBoxFileList.Location = New System.Drawing.Point(0, 0)
        Me.RichTextBoxFileList.Name = "RichTextBoxFileList"
        Me.RichTextBoxFileList.Size = New System.Drawing.Size(1068, 96)
        Me.RichTextBoxFileList.TabIndex = 0
        Me.RichTextBoxFileList.Text = ""
        Me.RichTextBoxFileList.WordWrap = False
        '
        'RichTextBoxErrorList
        '
        Me.RichTextBoxErrorList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.RichTextBoxErrorList.Location = New System.Drawing.Point(1091, 0)
        Me.RichTextBoxErrorList.Name = "RichTextBoxErrorList"
        Me.RichTextBoxErrorList.Size = New System.Drawing.Size(793, 96)
        Me.RichTextBoxErrorList.TabIndex = 1
        Me.RichTextBoxErrorList.Text = ""
        Me.RichTextBoxErrorList.WordWrap = False
        '
        'ProgressBar1
        '
        Me.ProgressBar1.Location = New System.Drawing.Point(411, 1)
        Me.ProgressBar1.Name = "ProgressBar1"
        Me.ProgressBar1.Size = New System.Drawing.Size(171, 23)
        Me.ProgressBar1.Style = System.Windows.Forms.ProgressBarStyle.Continuous
        Me.ProgressBar1.TabIndex = 2
        '
        'LineNumbers_For_RichTextBoxInput
        '
        Me.LineNumbers_For_RichTextBoxInput._SeeThroughMode_ = False
        Me.LineNumbers_For_RichTextBoxInput.AutoSizing = True
        Me.LineNumbers_For_RichTextBoxInput.BackgroundGradient_AlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbers_For_RichTextBoxInput.BackgroundGradient_BetaColor = System.Drawing.Color.LightSteelBlue
        Me.LineNumbers_For_RichTextBoxInput.BackgroundGradient_Direction = System.Drawing.Drawing2D.LinearGradientMode.Horizontal
        Me.LineNumbers_For_RichTextBoxInput.BorderLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxInput.BorderLines_Style = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbers_For_RichTextBoxInput.BorderLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.LineNumbers_For_RichTextBoxInput.DockSide = CSharpToVBApp.LineNumbers_For_RichTextBox.LineNumberDockSide.Left
        Me.LineNumbers_For_RichTextBoxInput.GridLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxInput.GridLines_Style = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbers_For_RichTextBoxInput.GridLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_Alignment = System.Drawing.ContentAlignment.TopRight
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_AntiAlias = True
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_AsHexadecimal = False
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_ClippedByItemRectangle = True
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_LeadingZeroes = True
        Me.LineNumbers_For_RichTextBoxInput.LineNrs_Offset = New System.Drawing.Size(0, 0)
        Me.LineNumbers_For_RichTextBoxInput.Location = New System.Drawing.Point(0, 0)
        Me.LineNumbers_For_RichTextBoxInput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbers_For_RichTextBoxInput.MarginLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxInput.MarginLines_Side = CSharpToVBApp.LineNumbers_For_RichTextBox.LineNumberDockSide.Right
        Me.LineNumbers_For_RichTextBoxInput.MarginLines_Style = System.Drawing.Drawing2D.DashStyle.Solid
        Me.LineNumbers_For_RichTextBoxInput.MarginLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxInput.Name = "LineNumbers_For_RichTextBoxInput"
        Me.LineNumbers_For_RichTextBoxInput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbers_For_RichTextBoxInput.ParentRichTextBox = Me.RichTextBoxConversionInput
        Me.LineNumbers_For_RichTextBoxInput.Show_BackgroundGradient = True
        Me.LineNumbers_For_RichTextBoxInput.Show_BorderLines = True
        Me.LineNumbers_For_RichTextBoxInput.Show_GridLines = True
        Me.LineNumbers_For_RichTextBoxInput.Show_LineNrs = True
        Me.LineNumbers_For_RichTextBoxInput.Show_MarginLines = True
        Me.LineNumbers_For_RichTextBoxInput.Size = New System.Drawing.Size(20, 80)
        Me.LineNumbers_For_RichTextBoxInput.TabIndex = 23
        Me.LineNumbers_For_RichTextBoxInput.Visible = False
        '
        'RichTextBoxConversionOutput
        '
        Me.RichTextBoxConversionOutput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.RichTextBoxConversionOutput.Dock = System.Windows.Forms.DockStyle.Right
        Me.RichTextBoxConversionOutput.Font = New System.Drawing.Font("Consolas", 11.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.RichTextBoxConversionOutput.HScrollPos = 0
        Me.RichTextBoxConversionOutput.Location = New System.Drawing.Point(855, 0)
        Me.RichTextBoxConversionOutput.Name = "RichTextBoxConversionOutput"
        Me.RichTextBoxConversionOutput.Size = New System.Drawing.Size(793, 80)
        Me.RichTextBoxConversionOutput.TabIndex = 10
        Me.RichTextBoxConversionOutput.Text = ""
        Me.RichTextBoxConversionOutput.VScrollPos = 0
        Me.RichTextBoxConversionOutput.WordWrap = False
        '
        'LineNumbers_For_RichTextBoxOutput
        '
        Me.LineNumbers_For_RichTextBoxOutput._SeeThroughMode_ = False
        Me.LineNumbers_For_RichTextBoxOutput.AutoSizing = True
        Me.LineNumbers_For_RichTextBoxOutput.BackgroundGradient_AlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbers_For_RichTextBoxOutput.BackgroundGradient_BetaColor = System.Drawing.Color.LightSteelBlue
        Me.LineNumbers_For_RichTextBoxOutput.BackgroundGradient_Direction = System.Drawing.Drawing2D.LinearGradientMode.Horizontal
        Me.LineNumbers_For_RichTextBoxOutput.BorderLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxOutput.BorderLines_Style = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbers_For_RichTextBoxOutput.BorderLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxOutput.DockSide = CSharpToVBApp.LineNumbers_For_RichTextBox.LineNumberDockSide.Left
        Me.LineNumbers_For_RichTextBoxOutput.GridLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxOutput.GridLines_Style = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbers_For_RichTextBoxOutput.GridLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_Alignment = System.Drawing.ContentAlignment.TopRight
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_AntiAlias = True
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_AsHexadecimal = False
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_ClippedByItemRectangle = True
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_LeadingZeroes = True
        Me.LineNumbers_For_RichTextBoxOutput.LineNrs_Offset = New System.Drawing.Size(0, 0)
        Me.LineNumbers_For_RichTextBoxOutput.Location = New System.Drawing.Point(836, 0)
        Me.LineNumbers_For_RichTextBoxOutput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbers_For_RichTextBoxOutput.MarginLines_Color = System.Drawing.Color.SlateGray
        Me.LineNumbers_For_RichTextBoxOutput.MarginLines_Side = CSharpToVBApp.LineNumbers_For_RichTextBox.LineNumberDockSide.Right
        Me.LineNumbers_For_RichTextBoxOutput.MarginLines_Style = System.Drawing.Drawing2D.DashStyle.Solid
        Me.LineNumbers_For_RichTextBoxOutput.MarginLines_Thickness = 1.0!
        Me.LineNumbers_For_RichTextBoxOutput.Name = "LineNumbers_For_RichTextBoxOutput"
        Me.LineNumbers_For_RichTextBoxOutput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbers_For_RichTextBoxOutput.ParentRichTextBox = Me.RichTextBoxConversionOutput
        Me.LineNumbers_For_RichTextBoxOutput.Show_BackgroundGradient = True
        Me.LineNumbers_For_RichTextBoxOutput.Show_BorderLines = True
        Me.LineNumbers_For_RichTextBoxOutput.Show_GridLines = True
        Me.LineNumbers_For_RichTextBoxOutput.Show_LineNrs = True
        Me.LineNumbers_For_RichTextBoxOutput.Show_MarginLines = True
        Me.LineNumbers_For_RichTextBoxOutput.Size = New System.Drawing.Size(18, 80)
        Me.LineNumbers_For_RichTextBoxOutput.TabIndex = 22
        Me.LineNumbers_For_RichTextBoxOutput.Visible = False
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1648, 552)
        Me.Controls.Add(Me.ProgressBar1)
        Me.Controls.Add(Me.LabelErrorCount)
        Me.Controls.Add(Me.ButtonStop)
        Me.Controls.Add(Me.SearchWhere)
        Me.Controls.Add(Me.PictureBox1)
        Me.Controls.Add(Me.ButtonSearch)
        Me.Controls.Add(Me.SearchDirection)
        Me.Controls.Add(Me.SearchInput)
        Me.Controls.Add(Me.VB2CSharp)
        Me.Controls.Add(Me.CSharp2VB)
        Me.Controls.Add(Me.SplitContainer1)
        Me.Controls.Add(Me.MenuStrip1)
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Name = "Form1"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Convert C# To VB"
        Me.MenuStrip1.ResumeLayout(False)
        Me.MenuStrip1.PerformLayout()
        Me.ContextMenuStrip1.ResumeLayout(False)
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents CSharp2VB As RadioButton
    Friend WithEvents VB2CSharp As RadioButton
    Friend WithEvents MenuStrip1 As MenuStrip
    Friend WithEvents FileToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents SaveAsToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents EditToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents CutToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents CopyToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents PasteToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents UndoToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents OptionsToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents MiscellaneousOptionsToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ConvertToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ConvertProjectToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ConvertFolderToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ConvertSnipitToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents HelpToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents SaveFileDialog1 As SaveFileDialog
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents ColorizeSourceToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents FIndToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripSeparator1 As ToolStripSeparator
    Friend WithEvents SearchInput As TextBox
    Friend WithEvents ImageList1 As ImageList
    Friend WithEvents SearchDirection As ComboBox
    Friend WithEvents ButtonSearch As Button
    Friend WithEvents PictureBox1 As PictureBox
    Friend WithEvents SearchWhere As ComboBox
    Friend WithEvents InputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents OutputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents ContextMenuStrip1 As ContextMenuStrip
    Friend WithEvents ToolStripMenuItem_Copy As ToolStripMenuItem
    Friend WithEvents ToolStripMenuItem_Cut As ToolStripMenuItem
    Friend WithEvents ToolStripMenuItem_Paste As ToolStripMenuItem
    Friend WithEvents PauseConvertOnSuccessToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripSeparator2 As ToolStripSeparator
    Friend WithEvents RecentFilesToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents RecentFile1ToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents RecentFoldersToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents RecentFolder1ToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ButtonStop As Button
    Friend WithEvents LabelErrorCount As Label
    Friend WithEvents CompileToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolTip1 As ToolTip
    Friend WithEvents AutoCompileToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripSeparator4 As ToolStripSeparator
    Friend WithEvents ToolStripSeparator3 As ToolStripSeparator
    Friend WithEvents SplitContainer1 As SplitContainer
    Friend WithEvents RichTextBoxConversionOutput As AdvancedRTB
    Friend WithEvents RichTextBoxConversionInput As RichTextBox
    Friend WithEvents RichTextBoxErrorList As RichTextBox
    Friend WithEvents LineNumbers_For_RichTextBoxInput As LineNumbers_For_RichTextBox
    Friend WithEvents LineNumbers_For_RichTextBoxOutput As LineNumbers_For_RichTextBox
    Friend WithEvents RichTextBoxFileList As RichTextBox
    Friend WithEvents StartFolderConvertFromLastFileToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ProgressBar1 As ProgressBar
    Friend WithEvents ExitToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripSeparator5 As ToolStripSeparator
    Friend WithEvents ToolStripSeparator6 As ToolStripSeparator
    Friend WithEvents SnippetToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents SnippetSaveToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents SnippetLoadLastToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripSeparator7 As ToolStripSeparator
    Friend WithEvents ViewToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents InputBufferLineNumbersToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents OuputBufferLineNumbersToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents DelayBetweenConversionsToolStripMenuItem As ToolStripComboBox
    Friend WithEvents SkipAutoGeneratedToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ColorizeResultToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents SkipTestResourceFilesToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents ToolStripMenuItem1 As ToolStripMenuItem
    Friend WithEvents OpenFileToolStripMenuItem1 As ToolStripMenuItem
    Friend WithEvents OpenProjectToolStripMenuItem As ToolStripMenuItem
End Class
